### ISSUE TITLE
Support Boolean target for binary classification

### ISSUE THREAD

**Issue by danielgafni** [dllllb/pytorch-lifestream#106]
Currently a `bool` target used for binary supervised classification causes a non-obvious error. 
It's not converted to a torch.Tensor and is presented as `np.ndarray` in `padded_batch.payload`. This causes the following error:

```python
File ~/.cache/pypoetry/virtualenvs/ar-resp-vArrGwjy-py3.10/lib/python3.10/site-packages/ptls/frames/supervised/seq_to_target_dataset.py:39, in SeqToTargetDataset.collate_fn(self, padded_batch)
     37 del padded_batch.payload[self.target_col_name]
     38 if self.target_dtype is not None:
---> 39     target = target.to(dtype=self.target_dtype)
     40 return padded_batch, target

AttributeError: 'numpy.ndarray' object has no attribute 'to'
```

It would be nice if `bool` value would be converted to `Long` tensors.

**Comment by ivkireev86** [comment]
@danielgafni , fixed in #115 
`bool` target will be processed as `bool` tensor. `SeqToTargetDataset` can cast it to `long` via specifying `target_dtype=torch.long` attribute.
