### ISSUE TITLE
TrxEncoder bug

### ISSUE THREAD

**Issue by Ilykuleshov** [dllllb/pytorch-lifestream#124]
The property `TrxEncoder.category_max_size` breaks, since `TrxEncoder.embeddings.values()` are subclasses of nn.Embedding, and don't support dict-like access, required [here](https://github.com/dllllb/pytorch-lifestream/blob/7cc59aded4c88a5ce69646ae288e70e01d503c46/ptls/nn/trx_encoder/trx_encoder_base.py#L167)

**Comment by ivkireev86** [comment]
Also #129 with unit test for this bug

**Comment by ivkireev86** [comment]
@Ilykuleshov , thank you for contribution!
