### ISSUE TITLE
torch.stack in def collate_feature_dict

### ISSUE THREAD

**Issue by Ivanich-spb** [dllllb/pytorch-lifestream#77]
ptls/data_load/utils.py

Hello!

If the dataloader has a feature called target. And the batchsize is not a multiple of the length of the dataset, then an error pops up on the last batch: "Sizes of tensors must match except in dimension 0". Due to the use of torch.staсk when processing a feature startwith 'target'.

**Comment by ivkireev86** [comment]
@Ivanich-spb ,hello!
Could you show a code example to reproduce this error?

**Comment by Ivanich-spb** [comment]
If take your's public notebook for AMEX competition form kaggle:

train_dataloader = torch.utils.data.DataLoader(
    all_train_dataset,
    collate_fn=collate_feature_dict,
    num_workers=8,
    batch_size=512,
)
train_embeds = torch.vstack(trainer.predict(model, train_dataloader))

Works only, if batch_size=1. Because that dataset has a col named "target" and last batch has size less than 512, so torch.stack for 'target' col raise the error.

**Comment by ivkireev86** [comment]
I can't reproduce "Sizes of tensors must match except in dimension 0" error with `torch.stack`. But `torch.vstack` reproduce it.
Can you split the last row from your code:
```
predict_output = trainer.predict(model, train_dataloader)
# print here the shapes of batch
print([t.shape for t in predict_output])  # send me this output
train_embeds = torch.vstack(predict_output)
```

I expect the correct execution of `trainer.predict` and mismatch in predict_output shapes (which is a cause of error in `torch.vstack`).

**Comment by Ivanich-spb** [comment]
torch.stack in the def collate_feature_dict -> ptls/data_load/utils.py

if type(v[0]) is torch.Tensor:
            if k.startswith('target'):
                new_x[k] = torch.stack(v, dim=0)

**Comment by ivkireev86** [comment]
`target` prefix are used for distinguish sequential features and array columns.
Sequential may have a different length, arrays should have the same shape for all samples in dataset.
If your target columns is a sequential feature, I suggest to rename it. The simplest way to do it is `ptls.data_load.iterable_processing.FeatureRename`. Just add `FeatureRename({'target': 'sequential_target'})` into dataset `i_filter` list.

More information about `ptls` feature naming: https://dllllb.github.io/pytorch-lifestream/feature_naming/

**Comment by ivkireev86** [comment]
`model` has `torch.nn.Flatten(start_dim=0)` layer in the end. So output is 1d tensor os size `(B,)` - batch.
`vstack` can't work with it. Use `cat`, it concatenates 1d tensor along batch axis. `train_embeds = torch.cat(trainer.predict(model, train_dataloader))`
`vstack` works similar but for 2d tensors.

https://www.kaggle.com/code/ivkireev/amex-ptls-baseline-supervised-neural-networ-8f6d4b/
Notebook with corrections.

**Comment by Ivanich-spb** [comment]
It's not totally right.
If batch_size = 1, vstack works without errors and with 1d tensors too.

And if I do model.head = torch.nn.Identity, so on exit I have 2d tensor - error was raised.

**Comment by ivkireev86** [comment]
Sure,
if `batch_size = 1` and model output is probability then you `trainer.predict` is list with 1-element tensors. It worts with `vstack` and with `cat`.
```
>>> out = [torch.rand(1) for _ in range(10)]
>>> [t.shape for t in out]
[Out]: [torch.Size([1]), torch.Size([1]), torch.Size([1]), ...]

>>> torch.vstack(out).shape
[Out]: torch.Size([10, 1])

>>> torch.cat(out).shape
[Out]: torch.Size([10])
```

Pay attention that vstack add new dimention for such tensors.

For `batch_size=512` we have something like.
```
>>> out = [torch.rand(512), torch.rand(512), torch.rand(512), torch.rand(1)]
>>> [t.shape for t in out]
[Out]: [torch.Size([512]), torch.Size([512]), torch.Size([512]), torch.Size([1])]

>>> torch.vstack(out).shape
[Out]: RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 512 but got size 1 for tensor number 3 in the list.

# works without last element, but final shape is wrong
>>> torch.vstack(out[:-1]).shape
[Out]: torch.Size([3, 512])

# woks with correct whape
>>> torch.cat(out).shape
[Out]: torch.Size([1537])
```

If you do `model.head = torch.nn.Identity`, model output will be 2d tensor with size `B, H` and `trainer.predict` will be the list of such tensors with same `H` and different `B`. Both `vstack` and `cat` should works correct.
```
>>>out = [torch.rand(512, 128), torch.rand(512, 128), torch.rand(512, 128), torch.rand(1, 128)]
>>> [t.shape for t in out]
[Out]: [torch.Size([512, 128]), torch.Size([512, 128]), torch.Size([512, 128]), torch.Size([1, 128])]

>>> torch.vstack(out).shape
[Out]: torch.Size([1537, 128])

>>> torch.cat(out).shape
[Out]: torch.Size([1537, 128])

```

**Comment by ivkireev86** [comment]
I don't see any errors in your last notebook version.
Is this issue solved?

**Comment by Ivanich-spb** [comment]
Ok, thank you for patience
