### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by livington** [dllllb/pytorch-lifestream#97]
Hi!I got installation error using Kaggle kernel!

<img width="836" alt="image" src="https://user-images.githubusercontent.com/29087895/216241626-5072c552-1039-4e79-a598-2eded60f737f.png">

**Comment by FuTSy13** [comment]
Fixed in the latest commit
https://github.com/dllllb/pytorch-lifestream/commit/fc6fa0003d29165744081cfa42a0261e003cbcbd

**Comment by ivkireev86** [comment]
Fixed in #99
